const prices=[{price:1.79,acceptance:61.7,contribution:.61},{price:2.19,acceptance:51.7,contribution:.93},{price:2.59,acceptance:26.7,contribution:1.2}];
const weatherCities=[['Berlin',52.52,13.405],['Hamburg',53.551,9.993],['Munich',48.137,11.575]];
const normal=()=>{let u=0,v=0;while(!u)u=Math.random();while(!v)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)};const percentile=(values,p)=>values.slice().sort((a,b)=>a-b)[Math.floor((values.length-1)*p)];
const $=id=>document.getElementById(id);const state={price:1,mix:60,budget:120,timing:'Q2 2026'};
function money(v){return `€${v.toFixed(2)}`}
function render(){const p=prices[state.price];const premium=prices[2];const cac=Math.round(44-(state.budget-120)/30-(state.mix-60)/60);const ltvCac=(3.2+(state.mix-60)/250-(p.price-2.19)/3).toFixed(1);const payback=(8.6+(state.mix-60)/35-(state.budget-120)/80+(p.price-2.19)*1.7).toFixed(1);
 $('recPrice').textContent=money(p.price);$('priceValue').textContent=money(p.price);$('acceptance').textContent=p.acceptance+'%';$('overviewAcceptance').innerHTML=p.acceptance+'% <small>acceptance</small>';$('contribution').textContent=money(p.contribution);$('ltvCac').textContent=ltvCac+' : 1';$('payback').textContent=payback+' mo';$('mixValue').textContent=`${state.mix} / ${100-state.mix}`;$('budgetValue').textContent=`€${state.budget}k`;$('timingValue').textContent=state.timing;$('scenarioCac').textContent=`€${cac}`;$('overviewCac').innerHTML=`€${cac} <small>scenario CAC</small>`;
 const names=['Entry-price test','Balanced premium launch','Premium brand push'];$('scenarioName').textContent=names[state.price];
 $('recExplain').textContent=p.price===2.19?'€2.19 keeps acceptance above 50% while materially improving contribution versus the entry price. A blended launch lets LUMEN learn online and borrow credibility from premium shelves.':p.price===1.79?'€1.79 maximises acceptance, but the thinner contribution leaves less room to recover the €44 blended CAC. This is a volume-led bet that prioritises trial over premium signal.':'€2.59 delivers the strongest unit economics, but acceptance drops sharply. This is a premium-brand bet: it can work only if LUMEN proves unusually strong repeat purchase.';
 $('tradeoffTitle').textContent=p.price===2.19?'€2.19 is the balance point.':p.price===1.79?'€1.79 buys trial, not runway.':'€2.59 protects margin, not demand.';$('tradeoffCopy').textContent=p.price===2.19?'The premium price adds margin, but acceptance falls by almost half. The middle price protects demand while giving the business room to fund acquisition.':p.price===1.79?'The entry price is easiest to say yes to, but each sale contributes less toward acquisition and fixed launch costs.':'The premium price creates the best contribution per unit, but the acceptance penalty means the team must prove that positioning can overcome a higher first-purchase barrier.';
 const marketShift=Math.round((state.budget-120)/20+(state.mix-60)/20-(p.price-2.19)*12);const berlin=82+marketShift;const hamburg=76+Math.round((state.mix-60)/18);const munich=71+Math.round((p.price-2.19)*8-(state.mix-60)/25);$('berlinScore').textContent=berlin;$('hamburgScore').textContent=hamburg;$('munichScore').textContent=munich;$('marketTitle').textContent=state.mix>=65?'Retail-led launch: prioritise shelf-ready cities.':'Online-led launch: prioritise fast-learning cities.';$('berlinReason').textContent=state.budget>=150?'Largest testable opportunity with enough budget to support awareness.':'Highest category density and strongest functional-beverage fit.';$('hamburgReason').textContent=state.mix>=60?'Premium retail access improves the credibility loop.':'Efficient online learning and strong repeat potential.';$('munichReason').textContent=p.price===2.59?'Spending power supports premium pricing, but competition is stronger.':'Spending power is attractive, though price sensitivity needs testing.';
 $('positioningTitle').textContent=p.price===1.79?'Lead with accessible function.':p.price===2.19?'Own the space between.':'Lead with premium performance.';$('lumenPosition').innerHTML=`LUMEN<span>${money(p.price)}</span>`;
 $('timingTitle').textContent=state.timing==='Q1 2026'?'Launch early, but accept a higher demand risk.':state.timing==='Q2 2026'?'Launch in Q2, learn by Q3.':state.timing==='Q3 2026'?'Use Q3 to validate before the winter scale-up.':'Delay to Q4 only if inventory or proof is not ready.';$('riskCopy').textContent=state.budget<100?'A lean budget may not generate enough awareness to validate the positioning quickly.':p.price===2.59?'Premium pricing without repeat-purchase proof could make CAC look acceptable while hiding weak LTV.':'The main risk is scaling retail before online tests confirm repeat purchase and efficient CAC.';
 $('consequences').innerHTML=`<div class="consequence"><i>↳</i><span><b>${p.acceptance}% acceptance</b> is the estimated first-purchase response at this price.</span></div><div class="consequence"><i>↗</i><span>At ${money(p.price)}, each unit contributes <b>${money(p.contribution)}</b>; the scenario blends retail and online economics.</span></div><div class="consequence"><i>◎</i><span>This budget/mix implies <b>${ltvCac}:1 LTV:CAC</b> and an estimated <b>${payback} month payback</b>.</span></div><div class="consequence"><i>!</i><span>What you are choosing not to optimise: <b>${p.price===2.59?'maximum trial volume':'maximum unit margin'}</b>.</span></div>`;
 $('priceChart').innerHTML=prices.map((x,i)=>`<div class="bar-group"><div class="bar" style="height:${x.acceptance*2.25}px;background:var(--blue)"><span>${x.acceptance}%</span></div><div class="bar" style="height:${x.contribution*110}px;background:var(--amber)"><span>${money(x.contribution)}</span></div><div class="bar-label">€${x.price.toFixed(2)}</div></div>`).join('');}
 ['priceSlider','mixSlider','budgetSlider','timingSelect'].forEach(id=>$(id).addEventListener('input',e=>{if(id==='priceSlider')state.price=+e.target.value;if(id==='mixSlider')state.mix=+e.target.value;if(id==='budgetSlider')state.budget=+e.target.value;if(id==='timingSelect')state.timing=e.target.value;render()}));
 $('resetBtn').addEventListener('click',()=>{state.price=1;state.mix=60;state.budget=120;state.timing='Q2 2026';$('priceSlider').value=1;$('mixSlider').value=60;$('budgetSlider').value=120;$('timingSelect').value='Q2 2026';render()});render();

// Keep the sidebar highlight aligned with the section currently visible.
const navLinks=[...document.querySelectorAll('.nav-item')];
const trackedSections=navLinks.map(link=>document.querySelector(link.getAttribute('href'))).filter(Boolean);
const setActiveSection=id=>navLinks.forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${id}`));
navLinks.forEach(link=>link.addEventListener('click',()=>setActiveSection(link.getAttribute('href').slice(1))));
const sectionObserver=new IntersectionObserver(entries=>{
  const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];
  if(visible) setActiveSection(visible.target.id);
},{rootMargin:'-18% 0px -62% 0px',threshold:[0,.15,.35]});
trackedSections.forEach(section=>sectionObserver.observe(section));
async function loadWeather(){try{const results=await Promise.all(weatherCities.map(async([city,latitude,longitude])=>{const response=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&daily=temperature_2m_max,precipitation_sum&forecast_days=7&timezone=Europe%2FBerlin`);if(!response.ok)throw new Error('weather request failed');const data=await response.json();const temperatures=data.daily.temperature_2m_max.filter(Number.isFinite);const rain=data.daily.precipitation_sum.filter(Number.isFinite).reduce((sum,value)=>sum+value,0);return{city,temp:temperatures.reduce((sum,value)=>sum+value,0)/temperatures.length,rain}}));const signal=results.sort((a,b)=>(b.temp-b.rain*.05)-(a.temp-a.rain*.05))[0];const demand=signal.temp>=20?'Warm conditions support an outdoor-led launch.':signal.rain>=20?'Wet conditions favour online discovery and delivery.':'Moderate conditions keep the blended launch balanced.';$('weatherStatus').textContent=`Live Open-Meteo signal · ${signal.city}: ${signal.temp.toFixed(1)}°C average high, ${signal.rain.toFixed(1)}mm rain next 7 days. ${demand}`}catch(error){$('weatherStatus').textContent='Live weather unavailable; using the case seasonality baseline. Forecast remains fully usable offline.'}}
loadWeather();
function runSimulation(){const p=prices[state.price],mix=state.mix/100,budget=state.budget,delay=state.timing==='Q1 2026'?0:state.timing==='Q2 2026'?1:state.timing==='Q3 2026'?2:3,rows=[];for(let i=0;i<500;i++){const cac=Math.max(18,44-(budget-120)/30-(state.mix-60)/60+normal()*7),conversion=Math.max(.025,p.acceptance/100+normal()*.055),repurchase=Math.min(.8,Math.max(.12,.42-(p.price-2.19)*.13+normal()*.09)),season=Math.max(.65,1+normal()*.14-delay*.025),retailMargin=Math.max(.2,p.contribution+normal()*.12),onlineMargin=Math.max(.2,p.contribution+.12+normal()*.1),units=Math.max(0,budget*1000/cac*conversion*repurchase*season*(1-delay*.06)),margin=units*(mix*retailMargin+(1-mix)*onlineMargin),ltvCac=Math.max(.4,3.2*(p.contribution/.93)*(repurchase/.42)*((p.acceptance/100)/.517)*(44/cac)*(1-delay*.04)+normal()*.25),payback=Math.max(3,8.6+(cac-44)/7-(repurchase-.42)*7-(p.contribution/.93-1)*1.5-(budget-120)/80+delay*.35+normal()*.35);rows.push({units,margin,ltvCac,payback})}const ltv=rows.filter(r=>r.ltvCac>3.1).length/500,pb=rows.filter(r=>r.payback<=9).length/500,sales=rows.map(r=>r.units),margins=rows.map(r=>r.margin),paybacks=rows.map(r=>r.payback);$('simLtvProbability').textContent=`${Math.round(ltv*100)}%`;$('simPaybackProbability').textContent=`${Math.round(pb*100)}%`;$('simSalesRange').textContent=`${Math.round(percentile(sales,.1)).toLocaleString()}–${Math.round(percentile(sales,.9)).toLocaleString()}`;$('simMarginRange').textContent=`€${Math.round(percentile(margins,.1)).toLocaleString()}–€${Math.round(percentile(margins,.9)).toLocaleString()}`;$('simScenarioText').textContent=`At €${p.price.toFixed(2)}, uncertainty spans CAC, conversion, 60-day repurchase, channel margin, seasonality and launch delay.`;const sensitivity=[['Repurchase within 60 days',.09],['CAC',.07],['Conversion rate',.055],['Seasonal demand',.14],['Launch delay',delay*.025+.025]].sort((a,b)=>b[1]-a[1])[0];$('simSensitivity').textContent=`Highest risk driver: ${sensitivity[0]}`;const scores=[['Growth',Math.min(99,Math.round(p.acceptance*.7+(1-mix)*20+budget/10))],['Margin',Math.min(99,Math.round(p.contribution/1.2*70+mix*20))],['Learning',Math.min(99,Math.round((1-mix)*55+budget/5))],['Risk',Math.min(99,Math.round((ltv*100+Math.max(0,100-pb*100))/2))]];scores.forEach(([name,value])=>{$(`score${name}`).style.width=`${value}%`;$(`score${name}Value`).textContent=value});const scenarios=[['Pessimistic',.1],['Base',.5],['Optimistic',.9]];$('simScenarioTable').innerHTML='<div class="sim-table-row sim-table-head"><span>Scenario</span><span>Sales</span><span>Margin</span><span>Payback</span></div>'+scenarios.map(([name,q])=>`<div class="sim-table-row"><strong>${name}</strong><span>${Math.round(percentile(sales,q)).toLocaleString()}</span><span>€${Math.round(percentile(margins,q)).toLocaleString()}</span><span>${percentile(paybacks,q).toFixed(1)} mo</span></div>`).join('')}
['priceSlider','mixSlider','budgetSlider','timingSelect'].forEach(id=>$(id).addEventListener('input',runSimulation));runSimulation();
